{% set version = "1.0.6" %}
{% set github = "https://github.com/SwissClinicalTrialOrganisation/secuTrialR" %}

package:
  name: r-secutrialr
  version: {{ version }}

source:
  url: {{ github }}/archive/{{ version }}.tar.gz
  sha256: b3b5542cbc9f2ac60643dd2b9e0badc01c3debd4798d9e5fa8f6dcb19e3d0c1f

build:
  noarch: generic
  number: 0
  script:
    - $R CMD INSTALL --build .            # [not win]
    - '"%R%" CMD INSTALL --build .'    # [win]

requirements:
  host:
    - r-base
    - r-haven >=2.2.0
    - r-readr
    - r-readxl
    - r-tcltk2
    - r-igraph
    - r-stringr
    - r-tibble
    - r-magrittr
    - r-purrr
    - r-tidyr
    - r-dplyr
    - r-rlang
    - r-lubridate
    - r-knitr
    - r-rmarkdown
    - r-testthat
    - r-tufte
    - r-lintr
  run:
    - r-base
    - r-haven >=2.2.0
    - r-readr
    - r-readxl
    - r-tcltk2
    - r-igraph
    - r-stringr
    - r-tibble
    - r-magrittr
    - r-purrr
    - r-tidyr
    - r-dplyr
    - r-rlang
    - r-lubridate
    - r-knitr
    - r-rmarkdown
    - r-testthat
    - r-tufte
    - r-lintr

test:
  commands:
    - $R -e "library('secuTrialR')"       # [not win]
    - "\"%R%\" -e \"library('secuTrialR')\""  # [win]

about:
  home: https://swissclinicaltrialorganisation.github.io/secuTrialR/
  dev_url: {{ github }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Handling of Data from the Clinical Data Management System secuTrial

extra:
  recipe-maintainers:
    - PatrickRWright
    - conda-forge/r
