{% set version = "1.1.0" %}
{% set github = "https://github.com/SwissClinicalTrialOrganisation/secuTrialR" %}

package:
  name: r-secutrialr
  version: {{ version }}

source:
  url: {{ github }}/archive/{{ version }}.tar.gz
  sha256: c82eb41bd1d866944ca213abcc351cebe10815a267958b0af05352667eb21c49

build:
  noarch: generic
  number: 0
  script:
    - $R CMD INSTALL --build .            # [not win]
    - '"%R%" CMD INSTALL --build .'    # [win]

requirements:
  host:
    - r-base
    - r-haven >=2.2.0
    - r-readr
    - r-readxl
    - r-tcltk2
    - r-igraph
    - r-stringr
    - r-tibble
    - r-magrittr
    - r-purrr
    - r-tidyr
    - r-dplyr
    - r-rlang
    - r-lubridate
    - r-knitr
    - r-rmarkdown
    - r-testthat
    - r-tufte
    - r-lintr
  run:
    - r-base
    - r-haven >=2.2.0
    - r-readr
    - r-readxl
    - r-tcltk2
    - r-igraph
    - r-stringr
    - r-tibble
    - r-magrittr
    - r-purrr
    - r-tidyr
    - r-dplyr
    - r-rlang
    - r-lubridate
    - r-knitr
    - r-rmarkdown
    - r-testthat
    - r-tufte
    - r-lintr

test:
  commands:
    - $R -e "library('secuTrialR')"       # [not win]
    - "\"%R%\" -e \"library('secuTrialR')\""  # [win]

about:
  home: https://swissclinicaltrialorganisation.github.io/secuTrialR/
  dev_url: {{ github }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Handling of Data from the Clinical Data Management System secuTrial

extra:
  recipe-maintainers:
    - PatrickRWright
    - conda-forge/r
