{% set version = '1.3.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-secutrialr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/secuTrialR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/secuTrialR/secuTrialR_{{ version }}.tar.gz
  sha256: e27933215bcab3183851337348c54c8ab783667f5d5e18e17af76182df76ddbc

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-haven >=2.2.0
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-readr
    - r-readxl
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-haven >=2.2.0
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-readr
    - r-readxl
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('secuTrialR')"           # [not win]
    - "\"%R%\" -e \"library('secuTrialR')\""  # [win]

about:
  home: https://github.com/SwissClinicalTrialOrganisation/secuTrialR
  license: MIT
  summary: Seamless and standardized interaction with data exported from the clinical data management
    system (CDMS) 'secuTrial'<https://www.secutrial.com>. The primary data export the
    package works with is a standard non-rectangular export.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - PatrickRWright
