{% set version = "1.1.1" %}
{% set github = "https://github.com/SwissClinicalTrialOrganisation/secuTrialR" %}

package:
  name: r-secutrialr
  version: {{ version }}

source:
  url: {{ github }}/archive/{{ version }}.tar.gz
  sha256: fd8df070047a50ec30fee308d801c3b0bbc0e28717050efd39e4db17d8ecd6b2

build:
  noarch: generic
  number: 1
  script:
    - $R CMD INSTALL --build .            # [not win]
    - '"%R%" CMD INSTALL --build .'    # [win]

requirements:
  host:
    - r-base
    - r-dplyr
    - r-haven >=2.2.0
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-readr
    - r-readxl
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-haven >=2.2.0
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-readr
    - r-readxl
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('secuTrialR')"       # [not win]
    - "\"%R%\" -e \"library('secuTrialR')\""  # [win]

about:
  home: https://swissclinicaltrialorganisation.github.io/secuTrialR/
  dev_url: {{ github }}
  license: MIT
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
  summary: Handling of Data from the Clinical Data Management System secuTrial

extra:
  recipe-maintainers:
    - PatrickRWright
    - conda-forge/r
